/**
 * Graph export utilities.
 *
 * Exports the React Flow canvas as SVG or PNG without any extra dependencies.
 * Uses the native SVG already rendered by React Flow's `.react-flow__renderer`
 * and rasterizes it for PNG output via canvas.
 */

/**
 * Find the React Flow viewport SVG/canvas container.
 */
function findReactFlowElement(): { svg: SVGSVGElement; host: HTMLElement } | null {
    // The .react-flow wrapper is the outermost container
    const host = document.querySelector('.react-flow') as HTMLElement | null;
    if (!host) return null;
    // Edges live in a sibling SVG
    const svg = host.querySelector('.react-flow__edges') as SVGSVGElement | null;
    if (!svg) return null;
    return { svg, host };
}

/**
 * Clone the React Flow DOM into a self-contained SVG string.
 * Captures:
 *   - Edges (already an SVG layer)
 *   - Nodes (via HTML → foreignObject embedding)
 *   - Current viewport transform
 */
function buildSvgString(theme: 'dark' | 'light' = 'dark'): string | null {
    const rf = findReactFlowElement();
    if (!rf) return null;
    const { host } = rf;

    const rect = host.getBoundingClientRect();
    const width = Math.max(1, Math.round(rect.width));
    const height = Math.max(1, Math.round(rect.height));

    // Get the current viewport transform (pan/zoom)
    const viewport = host.querySelector('.react-flow__viewport') as HTMLElement | null;
    const transform = viewport?.style.transform || '';

    // Find edges SVG content
    const edgesSvg = host.querySelector('.react-flow__edges') as SVGSVGElement | null;
    const edgesContent = edgesSvg?.innerHTML || '';

    // Find each node and render as foreignObject containing a div clone
    const nodeWrappers = Array.from(
        host.querySelectorAll('.react-flow__node'),
    ) as HTMLElement[];

    const nodeElements = nodeWrappers
        .map((wrap) => {
            const x = parseFloat(wrap.style.transform.match(/translate\(([^,]+)px/)?.[1] ?? '0');
            const y = parseFloat(wrap.style.transform.match(/,\s*([^)]+)px/)?.[1] ?? '0');
            const w = wrap.offsetWidth || 240;
            const h = wrap.offsetHeight || 100;
            const clone = wrap.cloneNode(true) as HTMLElement;
            clone.style.transform = '';
            clone.style.position = 'static';
            // Inline computed background/border for the container
            const cs = getComputedStyle(wrap);
            clone.style.background = cs.background || '';
            clone.style.fontFamily = cs.fontFamily || 'system-ui, sans-serif';
            const html = clone.outerHTML;
            return `<foreignObject x="${x}" y="${y}" width="${w}" height="${h}">
                <div xmlns="http://www.w3.org/1999/xhtml">${html}</div>
            </foreignObject>`;
        })
        .join('\n');

    const bg = theme === 'dark' ? '#0a0a0f' : '#ffffff';
    const textColor = theme === 'dark' ? '#e4e4e7' : '#111827';

    return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xhtml="http://www.w3.org/1999/xhtml"
     width="${width}"
     height="${height}"
     viewBox="0 0 ${width} ${height}">
  <style>
    text { font-family: system-ui, -apple-system, sans-serif; fill: ${textColor}; }
    .react-flow__edge-path { fill: none; }
  </style>
  <rect x="0" y="0" width="${width}" height="${height}" fill="${bg}"/>
  <g style="transform: ${transform}">
    <g class="edges">${edgesContent}</g>
    <g class="nodes">${nodeElements}</g>
  </g>
  <text x="${width - 12}" y="${height - 10}"
        text-anchor="end"
        fill="${textColor}"
        opacity="0.4"
        font-size="11">
    Generated by Archy · github.com/kvmil6/Archy
    </text>
</svg>`;
}

/**
 * Trigger a download of the current graph as an SVG file.
 */
export function exportGraphAsSvg(filename = 'archy-architecture.svg', theme: 'dark' | 'light' = 'dark'): boolean {
    const svgString = buildSvgString(theme);
    if (!svgString) return false;
    const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
    triggerDownload(blob, filename);
    return true;
}

/**
 * Trigger a download of the current graph as a PNG file.
 * Rasterizes the SVG via a canvas at 2x pixel density for retina displays.
 */
export async function exportGraphAsPng(
    filename = 'archy-architecture.png',
    theme: 'dark' | 'light' = 'dark',
    scale = 2,
): Promise<boolean> {
    const svgString = buildSvgString(theme);
    if (!svgString) return false;
    const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    try {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        await new Promise<void>((resolve, reject) => {
            img.onload = () => resolve();
            img.onerror = (e) => reject(new Error(`Image load failed: ${String(e)}`));
            img.src = url;
        });

        const host = document.querySelector('.react-flow') as HTMLElement | null;
        const rect = host?.getBoundingClientRect();
        const w = Math.round((rect?.width ?? img.width) * scale);
        const h = Math.round((rect?.height ?? img.height) * scale);
        const canvas = document.createElement('canvas');
        canvas.width = w;
        canvas.height = h;
        const ctx = canvas.getContext('2d');
        if (!ctx) throw new Error('Canvas 2D context unavailable');
        ctx.fillStyle = theme === 'dark' ? '#0a0a0f' : '#ffffff';
        ctx.fillRect(0, 0, w, h);
        ctx.drawImage(img, 0, 0, w, h);

        const pngBlob = await new Promise<Blob | null>((resolve) =>
            canvas.toBlob((b) => resolve(b), 'image/png'),
        );
        if (!pngBlob) throw new Error('Canvas toBlob returned null');
        triggerDownload(pngBlob, filename);
        return true;
    } finally {
        URL.revokeObjectURL(url);
    }
}

/**
 * Export graph structure as JSON (nodes + edges + metadata).
 * Useful for archiving or sharing the architecture snapshot.
 */
export function exportGraphAsJson(
    nodes: unknown[],
    edges: unknown[],
    metadata: Record<string, unknown> = {},
    filename = 'archy-architecture.json',
): void {
    const payload = {
        generator: 'Archy',
        generated_at: new Date().toISOString(),
        ...metadata,
        nodes,
        edges,
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], {
        type: 'application/json;charset=utf-8',
    });
    triggerDownload(blob, filename);
}

function triggerDownload(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
}
