"""
Feature 8 — Architecture Decision Records (ADR) Auto-Generation.

After detecting graph changes (via diff), generates human-readable
architecture decision records summarising what changed and why it matters.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


def generate_adr(
    diff_data: dict[str, Any],
    project_name: str = "Project",
    health_before: int | None = None,
    health_after: int | None = None,
) -> dict[str, Any]:
    """
    Generate an ADR from a snapshot diff.

    diff_data should match the format from /snapshots/diff:
      {nodes_added, nodes_removed, nodes_modified, edges_added, edges_removed, ...}
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    nodes_added = diff_data.get("nodes_added", [])
    nodes_removed = diff_data.get("nodes_removed", [])
    edges_added = diff_data.get("edges_added", [])
    edges_removed = diff_data.get("edges_removed", [])

    # Determine the nature of the change
    change_types: list[str] = []
    if len(nodes_added) > len(nodes_removed):
        change_types.append("expansion")
    if len(nodes_removed) > len(nodes_added):
        change_types.append("simplification")
    if len(edges_removed) > 0 and len(edges_added) == 0:
        change_types.append("decoupling")
    if len(edges_added) > len(edges_removed):
        change_types.append("increased coupling")

    if not change_types:
        change_types = ["modification"]

    # Build title
    title_parts = []
    if nodes_added:
        labels = [n.get("label", n.get("id", "?")) for n in nodes_added[:3]]
        title_parts.append(f"Added {', '.join(labels)}" + (f" (+{len(nodes_added) - 3} more)" if len(nodes_added) > 3 else ""))
    if nodes_removed:
        labels = [n.get("label", n.get("id", "?")) for n in nodes_removed[:3]]
        title_parts.append(f"Removed {', '.join(labels)}" + (f" (+{len(nodes_removed) - 3} more)" if len(nodes_removed) > 3 else ""))
    if edges_added and not nodes_added:
        title_parts.append(f"{len(edges_added)} new dependencies")
    if edges_removed and not nodes_removed:
        title_parts.append(f"{len(edges_removed)} dependencies removed")

    title = "; ".join(title_parts) if title_parts else "Architecture update"

    # Build context section
    context_lines = [
        f"Project: {project_name}",
        f"Date: {now}",
        f"Change type: {', '.join(change_types)}",
    ]

    # Build decision section
    decision_lines = []
    if nodes_added:
        decision_lines.append(f"**Added {len(nodes_added)} node(s):** " + ", ".join(
            n.get("label", n.get("id", "?")) for n in nodes_added[:5]
        ))
    if nodes_removed:
        decision_lines.append(f"**Removed {len(nodes_removed)} node(s):** " + ", ".join(
            n.get("label", n.get("id", "?")) for n in nodes_removed[:5]
        ))
    if edges_added:
        decision_lines.append(f"**Added {len(edges_added)} edge(s)** (new dependencies)")
    if edges_removed:
        decision_lines.append(f"**Removed {len(edges_removed)} edge(s)** (decoupled modules)")

    # Build consequences section
    consequences = []
    if "decoupling" in change_types:
        consequences.append("Reduced coupling improves testability and module independence.")
    if "expansion" in change_types:
        consequences.append("New components increase the surface area. Ensure test coverage.")
    if "simplification" in change_types:
        consequences.append("Fewer components reduce maintenance burden.")
    if "increased coupling" in change_types:
        consequences.append("Increased coupling may reduce modularity. Monitor for circular dependencies.")

    if health_before is not None and health_after is not None:
        delta = health_after - health_before
        if delta > 0:
            consequences.append(f"Health score improved: {health_before} → {health_after} (+{delta})")
        elif delta < 0:
            consequences.append(f"Health score declined: {health_before} → {health_after} ({delta})")
        else:
            consequences.append(f"Health score unchanged at {health_after}.")

    if not consequences:
        consequences.append("No significant structural impact detected.")

    # Build markdown
    adr_number = int(datetime.now(timezone.utc).timestamp()) % 10000
    markdown = f"""# ADR-{adr_number:04d}: {title}

## Status
Accepted — auto-generated by Archy

## Date
{now}

## Context
{chr(10).join('- ' + c for c in context_lines)}

## Decision
{chr(10).join('- ' + d for d in decision_lines) if decision_lines else '- Minor structural update'}

## Consequences
{chr(10).join('- ' + c for c in consequences)}

---
*Auto-generated by Archy Architecture Intelligence.*
"""

    return {
        "adr_number": adr_number,
        "title": title,
        "markdown": markdown,
        "change_types": change_types,
        "stats": {
            "nodes_added": len(nodes_added),
            "nodes_removed": len(nodes_removed),
            "edges_added": len(edges_added),
            "edges_removed": len(edges_removed),
        },
        "health_delta": (health_after - health_before) if health_before is not None and health_after is not None else None,
        "generated_at": now,
    }
